# Copy this file to ${HOME} and change it accordingly. This file contains a configuration for docker runner common for
# all MLCube. This file is merged with a concrete MLCube configuration file.
docker:
  # Executable (docker, podman, sudo docker ...).
  docker: docker
  # Build a docker image every time a task is executed ("docker build ..." with cache).
  build_always: True
  # Docker run arguments when accelerator_count == 0.
  cpu_args: >-
    --rm  --net=host --uts=host --ipc=host --ulimit stack=67108864 --ulimit memlock=-1
    --privileged=true --security-opt seccomp=unconfined
  # Docker run arguments when accelerator_count > 0.
  gpu_args: >-
    --rm  --gpus=all --net=host --uts=host --ipc=host --ulimit stack=67108864 --ulimit memlock=-1
    --privileged=true --security-opt seccomp=unconfined
  # Environmental variables for run phase (-e NAME=VALUE).
  env_args:
    http_proxy: "${oc.env:http_proxy}"
    https_proxy: "${oc.env:https_proxy}"
  # Arguments for build phase (--build-args NAME=VALUE).
  build_args:
    http_proxy: "${oc.env:http_proxy}"
    https_proxy: "${oc.env:http_proxy}"
